//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shazzam.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath_LastFx {
            get {
                return ((string)(this["FilePath_LastFx"]));
            }
            set {
                this["FilePath_LastFx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath_LastImage {
            get {
                return ((string)(this["FilePath_LastImage"]));
            }
            set {
                this["FilePath_LastImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderPath_FX {
            get {
                return ((string)(this["FolderPath_FX"]));
            }
            set {
                this["FolderPath_FX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderPath_Images {
            get {
                return ((string)(this["FolderPath_Images"]));
            }
            set {
                this["FolderPath_Images"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("%DXSDK_DIR%\\Utilities\\bin\\x86\\fxc.exe")]
        public string DirectX_FxcPath {
            get {
                return ((string)(this["DirectX_FxcPath"]));
            }
            set {
                this["DirectX_FxcPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TabIndex_SelectedImage {
            get {
                return ((int)(this["TabIndex_SelectedImage"]));
            }
            set {
                this["TabIndex_SelectedImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow,Green")]
        public string ColorPickerColors {
            get {
                return ((string)(this["ColorPickerColors"]));
            }
            set {
                this["ColorPickerColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shazzam.Shaders")]
        public string GeneratedNamespace {
            get {
                return ((string)(this["GeneratedNamespace"]));
            }
            set {
                this["GeneratedNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IndentUsingTabs {
            get {
                return ((bool)(this["IndentUsingTabs"]));
            }
            set {
                this["IndentUsingTabs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int IndentSpaces {
            get {
                return ((int)(this["IndentSpaces"]));
            }
            set {
                this["IndentSpaces"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WPF")]
        public string TargetFramework {
            get {
                return ((string)(this["TargetFramework"]));
            }
            set {
                this["TargetFramework"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public double AnimationLengthDefault {
            get {
                return ((double)(this["AnimationLengthDefault"]));
            }
            set {
                this["AnimationLengthDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FolderPath_Output {
            get {
                return ((string)(this["FolderPath_Output"]));
            }
            set {
                this["FolderPath_Output"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilePath_LastMedia {
            get {
                return ((string)(this["FilePath_LastMedia"]));
            }
            set {
                this["FilePath_LastMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TabIndex_LastLoader {
            get {
                return ((int)(this["TabIndex_LastLoader"]));
            }
            set {
                this["TabIndex_LastLoader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Uri FilePath_TextureMap1 {
            get {
                return ((global::System.Uri)(this["FilePath_TextureMap1"]));
            }
            set {
                this["FilePath_TextureMap1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Uri FilePath_TextureMap2 {
            get {
                return ((global::System.Uri)(this["FilePath_TextureMap2"]));
            }
            set {
                this["FilePath_TextureMap2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Uri FilePath_TextureMap3 {
            get {
                return ((global::System.Uri)(this["FilePath_TextureMap3"]));
            }
            set {
                this["FilePath_TextureMap3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AreGeneratedCodeTabsEnabled {
            get {
                return ((bool)(this["AreGeneratedCodeTabsEnabled"]));
            }
            set {
                this["AreGeneratedCodeTabsEnabled"] = value;
            }
        }
    }
}
