//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shazzam.Shaders {
    using System.Windows;
    using System.Windows.Media;
    using System.Windows.Media.Effects;
    
    
    public class AutoGenShaderEffect : ShaderEffect {
        
        public static DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(AutoGenShaderEffect), 0);
        
        public static DependencyProperty DesaturationProperty = DependencyProperty.Register("Desaturation", typeof(double), typeof(AutoGenShaderEffect), new System.Windows.UIPropertyMetadata(new double(), PixelShaderConstantCallback(0)));
        
        public static DependencyProperty TonedProperty = DependencyProperty.Register("Toned", typeof(double), typeof(AutoGenShaderEffect), new System.Windows.UIPropertyMetadata(new double(), PixelShaderConstantCallback(1)));
        
        public static DependencyProperty LightcolorProperty = DependencyProperty.Register("Lightcolor", typeof(System.Windows.Media.Color), typeof(AutoGenShaderEffect), new System.Windows.UIPropertyMetadata(new System.Windows.Media.Color(), PixelShaderConstantCallback(2)));
        
        public static DependencyProperty DarkcolorProperty = DependencyProperty.Register("Darkcolor", typeof(System.Windows.Media.Color), typeof(AutoGenShaderEffect), new System.Windows.UIPropertyMetadata(new System.Windows.Media.Color(), PixelShaderConstantCallback(3)));
        
        public AutoGenShaderEffect(PixelShader shader) {
            PixelShader = shader;
            // Update each DependencyProperty that's registered with a shader register.
            // This is needed to ensure the shader gets sent the proper default value.
            this.UpdateShaderValue(InputProperty);
            this.UpdateShaderValue(DesaturationProperty);
            this.UpdateShaderValue(TonedProperty);
            this.UpdateShaderValue(LightcolorProperty);
            this.UpdateShaderValue(DarkcolorProperty);
        }
        
        public virtual System.Windows.Media.Brush Input {
            get {
                return ((System.Windows.Media.Brush)(GetValue(InputProperty)));
            }
            set {
                SetValue(InputProperty, value);
            }
        }
        
        public virtual double Desaturation {
            get {
                return ((double)(GetValue(DesaturationProperty)));
            }
            set {
                SetValue(DesaturationProperty, value);
            }
        }
        
        public virtual double Toned {
            get {
                return ((double)(GetValue(TonedProperty)));
            }
            set {
                SetValue(TonedProperty, value);
            }
        }
        
        public virtual System.Windows.Media.Color Lightcolor {
            get {
                return ((System.Windows.Media.Color)(GetValue(LightcolorProperty)));
            }
            set {
                SetValue(LightcolorProperty, value);
            }
        }
        
        public virtual System.Windows.Media.Color Darkcolor {
            get {
                return ((System.Windows.Media.Color)(GetValue(DarkcolorProperty)));
            }
            set {
                SetValue(DarkcolorProperty, value);
            }
        }
    }
}
