'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Windows
Imports System.Windows.Media
Imports System.Windows.Media.Effects

Namespace Shazzam.Shaders
    
    Public Class AutoGenShaderEffect
        Inherits ShaderEffect
        
        Public Shared InputProperty As DependencyProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", GetType(AutoGenShaderEffect), 0)
        
        Public Shared DesaturationProperty As DependencyProperty = DependencyProperty.Register("Desaturation", GetType(Double), GetType(AutoGenShaderEffect), New System.Windows.UIPropertyMetadata(New Double, PixelShaderConstantCallback(0)))
        
        Public Shared TonedProperty As DependencyProperty = DependencyProperty.Register("Toned", GetType(Double), GetType(AutoGenShaderEffect), New System.Windows.UIPropertyMetadata(New Double, PixelShaderConstantCallback(1)))
        
        Public Shared LightcolorProperty As DependencyProperty = DependencyProperty.Register("Lightcolor", GetType(System.Windows.Media.Color), GetType(AutoGenShaderEffect), New System.Windows.UIPropertyMetadata(New System.Windows.Media.Color, PixelShaderConstantCallback(2)))
        
        Public Shared DarkcolorProperty As DependencyProperty = DependencyProperty.Register("Darkcolor", GetType(System.Windows.Media.Color), GetType(AutoGenShaderEffect), New System.Windows.UIPropertyMetadata(New System.Windows.Media.Color, PixelShaderConstantCallback(3)))
        
        Public Sub New(ByVal shader As PixelShader)
            MyBase.New
            PixelShader = shader
            'Update each DependencyProperty that's registered with a shader register.
            'This is needed to ensure the shader gets sent the proper default value.
            Me.UpdateShaderValue(InputProperty)
            Me.UpdateShaderValue(DesaturationProperty)
            Me.UpdateShaderValue(TonedProperty)
            Me.UpdateShaderValue(LightcolorProperty)
            Me.UpdateShaderValue(DarkcolorProperty)
        End Sub
        
        Public Overridable Property Input() As System.Windows.Media.Brush
            Get
                Return CType(GetValue(InputProperty),System.Windows.Media.Brush)
            End Get
            Set
                SetValue(InputProperty, value)
            End Set
        End Property
        
        Public Overridable Property Desaturation() As Double
            Get
                Return CType(GetValue(DesaturationProperty),Double)
            End Get
            Set
                SetValue(DesaturationProperty, value)
            End Set
        End Property
        
        Public Overridable Property Toned() As Double
            Get
                Return CType(GetValue(TonedProperty),Double)
            End Get
            Set
                SetValue(TonedProperty, value)
            End Set
        End Property
        
        Public Overridable Property Lightcolor() As System.Windows.Media.Color
            Get
                Return CType(GetValue(LightcolorProperty),System.Windows.Media.Color)
            End Get
            Set
                SetValue(LightcolorProperty, value)
            End Set
        End Property
        
        Public Overridable Property Darkcolor() As System.Windows.Media.Color
            Get
                Return CType(GetValue(DarkcolorProperty),System.Windows.Media.Color)
            End Get
            Set
                SetValue(DarkcolorProperty, value)
            End Set
        End Property
    End Class
End Namespace
